### ISSUE TITLE
BUG: Error Kicked 'Pods Stream Connector requires the WordPress Stream plugin to be Activated to Work' when Stream is Active

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-stream#1]
This plugin hasn't been updated in 2 years, so it's possible Stream has changed it's name or some other such instance.

**Comment by sc0ttkclark** [comment]
Have them test with the latest Pods Stream on GitHub, I have some fixes in it right now.

**Comment by jimtrue** [comment]
As in the last 12 minutes? ;) 'cause I just tested.

**Comment by sc0ttkclark** [comment]
it's working on another site, I'll have a look

**Comment by jimtrue** [comment]
Yep, still kicking that error.

**Comment by sc0ttkclark** [comment]
Which version of Stream?

**Comment by jimtrue** [comment]
Never mind, I just updated mine to 0.20 Pods Stream and the error disappeared.

**Comment by jimtrue** [comment]
This version must not be pushed up to WordPress.org

**Comment by sc0ttkclark** [comment]
This one isn't up yet, that's right
